### ISSUE TITLE
[New Feature] loop full playlist VS a single audio

### ISSUE THREAD

**Issue by stanrisever** [florent37/Flutter-AssetsAudioPlayer#166]
New Feature : 

**android / ios / web / macos / web**

Change the playlist loop mode to make it loop the full playlist or a single audio

```
enum LoopState{
  none,
  single,
  playlist
}
```

**Comment by florent37** [comment]
ok I look for it

**Comment by florent37** [comment]
I tried the main.dart sample and it seems to work, can you try my sample ?

**Comment by florent37** [comment]
it you open one audio, it loop only this audio

if you open a playlist, it loop the full playlist (wait until the end of the playlist to play the first item)

**Comment by pro100svitlo** [comment]
I also found this issue.
So, from my point  expected behavior: if I enable loop, the current song should be looped.

Enother (and  probably betteer case) - create enum:
```dart
enum LoopState{
  none,
  single,
  playlist
}
```

`none` - loop disabled,
`single` - loop for current file enabled
`playlist` - loop for playlist enabled (if there only one file, then it will be looped)

**Comment by florent37** [comment]
Yes for the playlist case it would be useful

**Comment by stanrisever** [comment]
I use a playlist. I just want to loop single song.

**Comment by florent37** [comment]
I edit your issue to mark is as new feature & update the text

**Comment by florent37** [comment]
and i'm working on it :)

**Comment by florent37** [comment]
done, can you try the `2.0.2` please

you have a new class : LoopMode :)
