### ISSUE TITLE
Spotify integration

### ISSUE THREAD

**Issue by urmilshroff** [florent37/Flutter-AssetsAudioPlayer#227]
**Describe the feature you'd like**
Hey there! I haven't used this plugin (yet), but it looks extremely feature rich and very well made, so thank you for working on this!

I'd like to ask if playing music from Spotify (using their API) is supported yet, if it is a planned feature or if there is any way to do it well. I'm planning on making an all-in-one music player which can play audio from different sources, so just want to know how feasible it is.

Thanks!

**Comment by florent37** [comment]
It's not supported yet, I think it can be added, but in another package that use this library

It can be an awesome package btw, if you success to bind all spotify field (like artworkds, title, etc) with notifications, and all urls with Audio.streams or Audio.url :)

**Comment by florent37** [comment]
I mark it as closed because I don't think it will be directlu added inside this library sorry, it has to be a different package

But as I said, it's possible to use the AssetsAudioPlayer with any url, and providing headers to requests, so it's possible to create a player that use this lib to play spotify urls :)

**Comment by urmilshroff** [comment]
Thank you! I will try exploring options.
