### ISSUE TITLE
Swift Version attribut

### ISSUE THREAD

**Issue by steph29** [florent37/Flutter-AssetsAudioPlayer#230]
**Flutter Version**
1.12
My version : 
1.12
**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : iOS

**Describe the bug**
The application works good on Android, but on iOS, i have this message.

[!] Unable to determine Swift version for the following pods:

- `assets_audio_player` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Thanks

**Comment by florent37** [comment]
I think it's related to https://github.com/fayeed/flutter_freshchat/issues/9#issuecomment-514329934

**Comment by florent37** [comment]
can you try https://github.com/fayeed/flutter_freshchat/issues/9#issuecomment-514329934

Bridging Header must be created.
Open the project with XCode. Then choose File -> New -> File -> Swift File.
A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.).
XCode will ask you if you wish to create Bridging Header, click yes.
Make sure you have use_frameworks! in the Runner block, in ios/Podfile。
Make sure you have SWIFT_VERSION 4.2 selected in you XCode -> Build Settings
Do flutter clean.
Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update

**Comment by florent37** [comment]
because in my podscped I have `  s.swift_version    = '4.2'`

**Comment by florent37** [comment]
or as said here https://github.com/esysberlin/esys-flutter-share 
try to edit your podfile to setup version

```
target 'Runner' do
  use_frameworks!  # required by simple_permission
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2' 
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by florent37** [comment]
if it does not work, I just updated the podspec, I'll can send a new version to try https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/0e8b1a65ead4a79d4f1705774219f75628d42d26
