### ISSUE TITLE
Network  tracks hosted on aws are not being played in Ios

### ISSUE THREAD

**Issue by surpriso1997** [florent37/Flutter-AssetsAudioPlayer#246]
**Flutter Version**

My version : 1.17.1

**Lib Version**

My version : 2.0.6+3

**Platform (Android / iOS / web) + version**

Platform : ios

**Describe the bug**

Some of the network tracks aren't playing in Ios. The same track plays in android. Manually downloading the track from 
url and playing also works but doesn't play in the app.

While playing this platform exception is thrown:
```
flutter: PlatformException(PLAY_ERROR, Cannot play https://d14nt81hc5bide.cloudfront.net/M8v3Ay7vbAUDn9eWGJUEHgxV, Cannot Open)
```
**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by florent37** [comment]
Do you know the format of this audio ?

**Comment by surpriso1997** [comment]
> Do you know the format of this audio ?

Audios are in mp3 format

**Comment by surpriso1997** [comment]
@florent37 I enabled extra logs and this line is also shown before the above platform exception error message:
``` _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0ED12F70-6702-4377-9B38-57E24AD9F712>.<62>, NSLocalizedDescription=cancelled}
``

**Comment by florent37** [comment]
I tried also and cannot play if, even if I download it locally and try to play it. Maybe avplayer need the extension to plahy it.


I don't find any fix for this

**Comment by surpriso1997** [comment]
> I tried also and cannot play if, even if I download it locally and try to play it. Maybe avplayer need the extension to plahy it.
> 
> 
> I don't find any fix for this

I also think this is Avplayer's limitations, I found some Stack overflow thread discussing on this topics. Thanks for your efforts.

**Comment by florent37** [comment]
sorry...

**Comment by florent37** [comment]
I don't know, but maybe it's possible to have an url with the extension ? :/

**Comment by surpriso1997** [comment]
> 
> 
> I don't know, but maybe it's possible to have an url with the extension ? :/
We are trying to do the same thing.

**Comment by MichalBaranMiquido** [comment]
I also had a problem of Android working fine, but iOS crashing with this error:
`_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0ED12F70-6702-4377-9B38-57E24AD9F712>.<62>, NSLocalizedDescription=cancelled}`

After debugging with XCode, it got me to line:
`let image: UIImage = UIImage(contentsOfFile: imagePath)!`
in https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/ea37a154006a1427a4baa4ab223e427f37581686/ios/Classes/Music.swift#L280

The issue arises when I'm trying to show a notification with _webp_ image from _assets_.
Showing notification with webp image from network works well.
Showing notification with png image from assets also works well.

Just leaving it here, because maybe it will be helpful to someone else.

**Comment by BaranMichal25** [comment]
I also had a problem of Android working fine, but iOS crashing with this error:
`_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0ED12F70-6702-4377-9B38-57E24AD9F712>.<62>, NSLocalizedDescription=cancelled}`

After debugging with XCode, it got me to line:
`let image: UIImage = UIImage(contentsOfFile: imagePath)!`
in https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/ea37a154006a1427a4baa4ab223e427f37581686/ios/Classes/Music.swift#L280

The issue arises when I'm trying to show a notification with _webp_ image from _assets_.
Showing notification with webp image from network works well.
Showing notification with png image from assets also works well.

Just leaving it here, because maybe it will be helpful to someone else.
