### ISSUE TITLE
Examples using material design

### ISSUE THREAD

**Issue by dJani97** [florent37/Flutter-AssetsAudioPlayer#281]
Hi!

I've been using this library for an audioguide-like application.
The app is designed using the Material design, and the use of the neumorphic library in the examples made it harder for me to "paste" this player into my app, because I constantly had to find the material-equivalent of what you are using.

I get it, neumorphic looks cool, but it's not the standard in Flutter.
I think when designing the examples for your library, you should try to keep your code as minimalistic as possible. Relying so heavily on an external package makes understanding your code harder for a new user.

If you would use Material only, most developers could simply paste your example code into their code, customize it a little bit, and have a ready music player.

**Comment by liuchuancong** [comment]
It's just design!  you can do this by yourself!  come on!

**Comment by mahadydev** [comment]
Why people have to have everything done for them ! I just don't understand how lazy a developer can be .

**Comment by DariaKalashnik** [comment]
@liuchuancong , @mahadydev , 
Thank you for your hard work and for a great lib.

Here I cannot not agree with @dJani97  in a way. I tackled similar issue when started to learn Flutter.
It's not always about being lazy. The motivations can be different, including

1) Not everyone is professional in Flutter, there are beginners too
2) You may not know the situation, maybe someone needs something urgent for their project
3) It's a great thing to see implementation based on simple examples and customize it further later

**Comment by DomingoMG** [comment]
I do not think there is a need for design, it is a matter of the developer, learning tutorials and online courses.

**Comment by mahadydev** [comment]
The author literally asking package Creator to post example in a way so he can copy paste in project! I mean, if you don't like the neumorphic design you can customize your own design after implementing basic functionally which is nicely documented already. The example posted was never meant to be copy pasted. It was to show what the package can do and neumorphic what a nice touch because he also created the neumorphic package. And flutter is already a great tool for designing. It's not hard to design a material look unless you are very new and just started flutter. Then I suggest you to learn it more before creating any complected project.

Sorry if I made anyone unhappy.

**Comment by florent37** [comment]
It's just design, as said all comments, the library provide some listeners, and do not embed the neumorphic

I close this issue, I think you can create your design, and bind it with an asset audio player. I don't think I have to add multiple designs in the sample, it's just sample :)
