### ISSUE TITLE
Next song when screen is locked

### ISSUE THREAD

**Issue by karelhladky** [florent37/Flutter-AssetsAudioPlayer#362]
**Flutter Version** 2.0.9

**iOS** 14

Hi,
I have a playlist with two songs. When the first song is finished, the player doesn't play next in the queue when is screen locked but when is the application in foreground, everything is working. Code:

`audioPlayer.open(playlist, playInBackground: PlayInBackground.enabled, autoStart: false, showNotification: true);`

Also, I have `UIBackgroundModes = audio` in `Info.plist`

Any suggestions?
Thanks

**Comment by kalismeras61** [comment]
This is knowing issue. Doesn't fixed yet.

**Comment by ThalapathySiva** [comment]
@kalismeras61  @florent37  any update on this ?

**Comment by ajsatam** [comment]
@kalismeras61 @florent37 is anyone able to fix this issue?

**Comment by ajsatam** [comment]
@kalismeras61 @florent37 is anyone able to fix this issue?

**Comment by DomingoMG** [comment]
Help is needed to develop and improve the functionality of this repository.

**Comment by ThalapathySiva** [comment]
@DomingoMG  @kalismeras61  @florent37  
https://github.com/ryanheise/audio_service/blob/master/darwin/Classes/AudioServicePlugin.m ,  I tried running this plugin's example app and the notification actions in this plugin works perfectly, but this plugin does not suit my project. I guess this project uses objective C for IOS, but we have used swift for IOS I guess. Could we see this implementation to get some idea about fixing this issue ?

**Comment by kalismeras61** [comment]
@florent37 can you check this ?

**Comment by Alexookah** [comment]
@kalismeras61 
I checked the Swift implementation, but i couldn't find any playlist handling.
I guess the playerDidFinishPlaying observer should handle go to next when a player item finishes?

**Comment by kalismeras61** [comment]
I think , it is not a playlist issue, even when app is background next and prev buttons are not working.

**Comment by Alexookah** [comment]
@kalismeras61 
I just tested the implementation using a playlist with 3 remote mp3 urls and it seems its working even with next and previous buttons. 
I used the seekbar with my fix to fast forward the song right before it finishes in order to emulate the playlist if the playlist goes to the next song (using the app in background).

Sometimes, the playlist does not go to the next song when the stream finishes. Maybe this is the issue we are trying to find? 
Also when using the next and back buttons I realised that at the 3rd song it goes back to the 1st, but from the 1st it does not go to the 3rd. Is that correct?

**Comment by kalismeras61** [comment]
@Alexookah did you test this with emulator or real device, for some reason it is not working real device but works with emulator.

**Comment by Alexookah** [comment]
@kalismeras61 tested on real device. My device iPhone 11 IOS 14.

**Comment by kalismeras61** [comment]
@Alexookah  Ohh okay can you try also with network files ?

**Comment by Alexookah** [comment]
@kalismeras61 
Are you using an iPhone simulator?
https://stackoverflow.com/a/49817183/4334709

My tests were done in network remote mp3 files.

**Comment by kalismeras61** [comment]
@Alexookah no i am also using real device. Are you sure that songs are playing when your app is background ? ( not foreground) i have old version the plugin. Maybe below PR fixed the issue.  I will check it. 

https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/377/files

**Comment by Alexookah** [comment]
@kalismeras61 
Yes i am sure the app is in background.
I only noticed this warning/error in my xcode console:
`[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform
`
I am not sure whether the setPlaybackState is stil an apple bug or something is missing and is related to this issue.

`[MediaRemote] WARNING: Unexpected type for now playing key kMRMediaRemoteNowPlayingInfoElapsedTime (is CFType, should be CFNumber). Removing from now playing info dictionary.`
Maybe this is also related to my PR and have to change the https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/397 into a CFType parameter?

**Comment by kalismeras61** [comment]
@Alexookah it seems it is working latest one.

**Comment by Alexookah** [comment]
@kalismeras61 
Great. So close this ticket as resolved and merge my PR #397 ?

**Comment by kalismeras61** [comment]
@Alexookah it is merged. Closing this issue according to this fix https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/377

**Comment by markseery** [comment]
> @kalismeras61
> Yes i am sure the app is in background.
> I only noticed this warning/error in my xcode console:
> `[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform `
> I am not sure whether the setPlaybackState is stil an apple bug or something is missing and is related to this issue.
> 
> another minor log
> `[MediaRemote] WARNING: Unexpected type for now playing key kMRMediaRemoteNowPlayingInfoElapsedTime (is CFType, should be CFNumber). Removing from now playing info dictionary.`
> Maybe this is also related to my PR and have to change the #397 into a CFType parameter?

I'm still getting the "com.apple.mediaremote.set-playback-state" message. How was this addressed?

**Comment by BringTheChill** [comment]
I still get this message with "Ignoring setPlaybackState" too...

**Comment by yelkamel** [comment]
same for me

**Comment by sahilgarg156** [comment]
The same issue replicated in the latest version 
assets_audio_player: ^3.0.5


> **Flutter Version** 2.0.9
> 
> **iOS** 14
> 
> Hi, I have a playlist with two songs. When the first song is finished, the player doesn't play next in the queue when is screen locked but when is the application in foreground, everything is working. Code:
> 
> `audioPlayer.open(playlist, playInBackground: PlayInBackground.enabled, autoStart: false, showNotification: true);`
> 
> Also, I have `UIBackgroundModes = audio` in `Info.plist`
> 
> Any suggestions? Thanks
