### ISSUE TITLE
AssetAudioPlayer Closes After exiting App

### ISSUE THREAD

**Issue by mfaizk** [florent37/Flutter-AssetsAudioPlayer#465]
**Flutter Version**
Flutter 1.22.6

**Lib Version**
assets_audio_player: ^2.0.13+1
My version : 
assets_audio_player: ^2.0.13+1
Platform : 
Android 11
**Describe the bug**
Audio Player closes after exiting the app in which PlayInBackgroud is enable
Audio Player closes after exiting the app in which PlayInBackgroud is enable
**Small code to reproduce**
 try {
      await audioAssetplayer
          .open(
        Playlist(audios: this.audioList),
        autoStart: false,
        notificationSettings: NotificationSettings(
          seekBarEnabled: true,
          playPauseEnabled: true,
          nextEnabled: true,
          stopEnabled: true,
          prevEnabled: true,
        ),
        playInBackground: PlayInBackground.enabled,
        showNotification: true,
        headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplugPlayOnPlug,
        audioFocusStrategy:
            AudioFocusStrategy.request(resumeAfterInterruption: true),
      )
          .whenComplete(() {
        this.isLoaded = true;
      });
    } on Exception catch (e) {
      this.isLoaded = false;
    }
    this.isLoaded = false;

`

**Comment by Mayb3Nots** [comment]
This is expected behavior if you pressed the back button it will exit the app and will no longer run the flutter app. Unless you press the home button which moves the app to the background which is what that  `PlayInBackground.enabled` does. What you can do is assign a `WillPopScope` and then use this package [move_to_background](https://pub.dev/packages/move_to_background) and move the app to background when back button is pressed.

**Comment by mfaizk** [comment]
Yes i have already apply this trick 😅. And thankx😁
