### ISSUE TITLE
need   http: ^0.13.0 support 

### ISSUE THREAD

**Issue by adverthouse** [florent37/Flutter-AssetsAudioPlayer#484]
Because assets_audio_player >=2.0.14 depends on http ^0.12.2

**Comment by offline-first** [comment]
Have you try to add this in your `pubspec.yaml`?
```
dependency_overrides:
  http: ^0.13.0
```

**Comment by yvrez** [comment]
Hi 

adding the dependancy_overrides doesn't help. Still have this output : 
Because no versions of assets_audio_player match >2.0.14 <3.0.0 and assets_audio_player 2.0.14 depends on http ^0.12.2, assets_audio_player ^2.0.14 requires http ^0.12.2.

And because image_picker >=0.7.0 depends on image_picker_platform_interface ^2.0.0 which depends on http ^0.13.0, assets_audio_player ^2.0.14 is incompatible with image_picker >=0.7.0.

**Comment by adverthouse** [comment]
I added   http: ^0.13.0 and that is not working.

**Comment by adverthouse** [comment]
Because assets_audio_player >=2.0.13+5 depends on rxdart ^0.25.0 and geoflutterfire >=2.2.1 depends on rxdart ^0.24.1, assets_audio_player >=2.0.13+5 is incompatible with geoflutterfire >=2.2.1.
So, because cab_driver depends on both geoflutterfire ^2.2.1 and assets_audio_player ^2.0.14, version solving failed.

**Comment by yvrez** [comment]
fixed for http but still have an issue with path_provider : 
on assets_audio_player ^2.0.14 which depends on path_provider ^1.6.27, path_provider ^1.6.27 is required.
Thanks :)

**Comment by adverthouse** [comment]
@yvrez   path_provider: ^2.0.1 available.

**Comment by nohli** [comment]
> fixed for http but still have an issue with path_provider :
> on assets_audio_player ^2.0.14 which depends on path_provider ^1.6.27, path_provider ^1.6.27 is required.
> Thanks :)

```
dependency_overrides:
  path_provider: ^2.0.1
```

**Comment by kalismeras61** [comment]
http depends on Null safety closing for now.
