### ISSUE TITLE
Can't detect if song already finished

### ISSUE THREAD

**Issue by zgramming** [florent37/Flutter-AssetsAudioPlayer#499]
**Flutter Version**

My version : 

`Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-ID)`

**Lib Version**
```
assets_audio_player:
    git:
      url: https://github.com/nohli/Flutter-AssetsAudioPlayer
      ref: migrate-to-nnbd
```
Reference to [this](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/486#issuecomment-799050547)

**Platform (Android / iOS / web) + version**

`SH C02 (mobile) • 10.35.76.154:5555 • android-arm64  • Android 9 (API 28)`

**Describe the bug**

I want detect if song is finished, in documentation i found 2 function to listen this `players.playlistFinished.listen` & `players.playlistAudioFinished.listen`

But when my song is finished, those function not trigger anything. I think it's same with this [issue](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/235)

> Already used **PlayerBuilderExtension** and it didn't work either
```
_assetsAudioPlayer.builderIsPlaying(
     builder: (context, isPlaying) {
       return Text(isPlaying ? "Pause" : "Play");  
     }
)
```

![bug assetaudioplayer](https://user-images.githubusercontent.com/38829404/111798892-16780580-88fd-11eb-94bc-21b968f4fbb0.gif)

# Sample code 

> I used plugin **Flutter Riverpod**

```

/// Initialize Class AudioPlayers
final globalAudioPlayers = StateProvider<AssetsAudioPlayer>((ref) {
  final uuid = Uuid();
  final result = AssetsAudioPlayer.withId(uuid.v1());
  return result;
});


@override
  void initState() {
    WidgetsBinding.instance?.addPostFrameCallback((_) {
      final players = context.read(globalAudioPlayers).state;

      players.currentPosition.listen((currentDuration) {
        context.read(currentSongProvider).setDuration(currentDuration);
      });

      players.playlistFinished.listen(
        (finished) {
          if (finished) {
            debugPrint('1.) Finished song');
          }
        },
        onDone: () => debugPrint('1.) OnDone'),
        onError: (error) => debugPrint('1.) OnError $error'),
      );

      players.playlistAudioFinished.listen(
        (finished) {
          debugPrint('2.) Finished song $finished');
        },
        onDone: () => debugPrint('2.) OnDone'),
        onError: (error) => debugPrint('2.) OnError $error'),
      );
    });
    super.initState();
  }
```

**Comment by bringbackthedog** [comment]
I'm having the same issue. Based on the [code](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/235#issuecomment-648022081) posted by @florent37 on #235, it's looking like `players.playlistAudioFinished` only gets called when the `playlist` moves on the another song. 

I've noticed @florent37 that in [your example code](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/235#issuecomment-648022081), if we set `not-looping`, the counter never increments.  

I think the expected behaviour (at least for me) is that when the song reaches it's maximum duration, `players.playlistAudioFinished` gets called, no matter if the playlist moves on to another song or not. 

And just for info, one of the things that I'm trying to accomplish is to determine  whether or not the song needs to be played from the beginning. As it is now, if the song is done, and the user presses play (i.e.: we call `playOrPause`), it will pause/resume, even though there is nothing left to play. In this case I'd like to be able move the position to the start (i.e.: `seek 0` or something).

**Comment by bringbackthedog** [comment]
I've come up with a work-around in the meantime. Maybe it's useful to someone else.

I'm using  `.currentPosition` stream to to see if the current player position >= song duration. If so the song is done. 
(Note: In my case `.currentPosition != songDuration`, when the song is done.  The `.currentPosition` exceeds the `songDuration` by a few milliseconds). 

```dart
    AssetsAudioPlayer _mainPlayer = AssetsAudioPlayer();

    Duration songDuration =
        _mainPlayer.current.valueWrapper?.value?.audio.duration ??
            Duration.zero;

    StreamSubscription? _subscription;
     _subscription = _mainPlayer.currentPosition.listen(
      (Duration duration) {
        // true if current player position >= song duration
        bool done = duration.compareTo(songDuration) >= 0;
    
        if (done) {
          log("audio is done");
          log("The player is at: ${duration.toString()}, the song duration is: ${songDuration.toString()}  ");
          _subscription?.cancel();
        }
      },
    );
```

**Comment by kalismeras61** [comment]
@zgramming can you check latest version with example app. It is working as expected.

**Comment by zgramming** [comment]
![fixed-auto-next-song-asset-audio-players](https://user-images.githubusercontent.com/38829404/117933634-f3ca0200-b32b-11eb-8f20-54b1dec7cea1.gif)

@kalismeras61  I can confirm that in version ^ 3.0.3 + 3 the function to detect the song is complete can be fully functional.

I think, this case can be closed

**Comment by kalismeras61** [comment]
Thanks for the update. Closing.

**Comment by AbanoubWagih94** [comment]
@kalismeras61  man we need your help please…

**Comment by JesseChang** [comment]
I tried on macos and it's still not working. Should I file another issue?
